baseURL = 'http://www.masagu.dev/'
languageCode = 'en-us'
title = 'Masagu.dev'
theme = "masagu-dev-theme"
paginate = 10

[params]
  title = "Masagu.dev"
  description = "masagu.dev is a WIP............."
  message = "Masagu.dev is here"
  background = ""
  mastodon = "https://mastodon.green/@masagu"
  aboutPic = "images/front-page.webp"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    noHl = true
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.parser.attribute]
    block = true

[menus]
  [[menus.main]]
    name = "Blog"
    url = "/blog"
    weight = 1
    [[menus.main.params]]
      external = false
  [[menus.main]]
    name = "About"
    url = "https://www.linkedin.com/in/maria-salcedo-g/"
    weight = 2
    [[menus.main.params]]
      external = true
  [[menus.main]]
    name = "Q&A"
    url = "https://github.com/mariasalcedo/masagu.dev/discussions"
    weight = 3
    [[menus.main.params]]
      external = true
