baseURL = 'http://www.masagu.dev/'
languageCode = 'en-us'
title = 'Masagu.dev'
theme = "masagu-dev-theme"
paginate = 10

[params]
  title = "Masagu.dev"
  description = "masagu.dev is a WIP............."
  message = "Masagu.dev is here"
  background = ""
  mastodon = "https://mastodon.green/@masagu"

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = true
    style = 'monokai'
    tabWidth = 4
  [markup.goldmark.renderer]
    unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "https://www.github.com/mariasalcedo"
    weight = 3
  [[menu.main]]
    name = "Q&A"
    url = "https://github.com/mariasalcedo/masagu.dev/discussions"
    weight = 4
